import Foundation

let lustyLines = Deck(name: "Lusty Lines", icon: "💦", questions: [
    Question(id: UUID(), text: "Would you rather exchange flirty texts all day or have one intense conversation at night?", optionA: "Flirty texts", optionB: "Intense conversation", challengeA: "Write a line you'd text.", challengeB: "Share one bold sentence you'd say."),
    Question(id: UUID(), text: "Would you rather be complimented on your smile or your voice?", optionA: "Smile", optionB: "Voice", challengeA: "Give your best smile.", challengeB: "Say something in your most alluring tone."),
    Question(id: UUID(), text: "Would you rather read a steamy love letter or receive a playful voice note?", optionA: "Love letter", optionB: "Voice note", challengeA: "Read a sentence aloud.", challengeB: "Record a teasing word."),
    Question(id: UUID(), text: "Would you rather send a romantic poem or a suggestive riddle?", optionA: "Poem", optionB: "Riddle", challengeA: "Recite two lines of the poem.", challengeB: "Share the riddle's first clue."),
    Question(id: UUID(), text: "Would you rather receive an anonymous compliment or a signed confession?", optionA: "Anonymous compliment", optionB: "Signed confession", challengeA: "Guess who sent it.", challengeB: "Admit if you'd sign it."),
    Question(id: UUID(), text: "Would you rather whisper something in someone’s ear or have them whisper to you?", optionA: "Whisper to them", optionB: "Have them whisper to you", challengeA: "Whisper one word now.", challengeB: "Describe the feeling."),
    Question(id: UUID(), text: "Would you rather flirt face-to-face or over messages?", optionA: "Face-to-face", optionB: "Over messages", challengeA: "Share a look you'd give.", challengeB: "Share an emoji you'd send."),
    Question(id: UUID(), text: "Would you rather get a love note in your pocket or on your pillow?", optionA: "In pocket", optionB: "On pillow", challengeA: "Read it aloud.", challengeB: "Act out finding it."),
    Question(id: UUID(), text: "Would you rather say the first flirty thing or respond to one?", optionA: "Say first", optionB: "Respond", challengeA: "Say it now.", challengeB: "Give your reply."),
    Question(id: UUID(), text: "Would you rather have a conversation only in movie quotes or in song lyrics?", optionA: "Movie quotes", optionB: "Song lyrics", challengeA: "Share a quote.", challengeB: "Share a lyric."),
    Question(id: UUID(), text: "Would you rather leave a lipstick mark on a note or a spritz of your scent?", optionA: "Lipstick mark", optionB: "Scent", challengeA: "Describe the kiss mark.", challengeB: "Describe the scent."),
    Question(id: UUID(), text: "Would you rather receive a playful dare or a flirty challenge?", optionA: "Playful dare", optionB: "Flirty challenge", challengeA: "Give your dare.", challengeB: "Give your challenge."),
    Question(id: UUID(), text: "Would you rather use pet names or real names in a flirty moment?", optionA: "Pet names", optionB: "Real names", challengeA: "Say the pet name.", challengeB: "Say the real name."),
    Question(id: UUID(), text: "Would you rather blush from a compliment or make someone else blush?", optionA: "Blush yourself", optionB: "Make them blush", challengeA: "Say something that might make someone blush.", challengeB: "Describe the feeling of blushing."),
    Question(id: UUID(), text: "Would you rather send a morning flirt or a midnight one?", optionA: "Morning", optionB: "Midnight", challengeA: "Send your morning line.", challengeB: "Send your midnight line."),
    Question(id: UUID(), text: "Would you rather receive an 'I miss you' text or an 'I want you' text?", optionA: "'I miss you'", optionB: "'I want you'", challengeA: "Reply to it.", challengeB: "React without words."),
    Question(id: UUID(), text: "Would you rather trade winks or trade smirks?", optionA: "Winks", optionB: "Smirks", challengeA: "Give your wink.", challengeB: "Give your smirk."),
    Question(id: UUID(), text: "Would you rather pass a secret note or send a coded message?", optionA: "Secret note", optionB: "Coded message", challengeA: "Pass a note now.", challengeB: "Say your code."),
    Question(id: UUID(), text: "Would you rather leave a note in lipstick on the mirror or in chalk on the sidewalk?", optionA: "Mirror", optionB: "Sidewalk", challengeA: "Write your line.", challengeB: "Describe the scene."),
    Question(id: UUID(), text: "Would you rather be told you’re unforgettable or irresistible?", optionA: "Unforgettable", optionB: "Irresistible", challengeA: "Say why.", challengeB: "React in character."),
    Question(id: UUID(), text: "Would you rather be sent a photo of a smile or a handwritten note?", optionA: "Smile", optionB: "Handwritten note", challengeA: "Mimic the smile.", challengeB: "Write a short note."),
    Question(id: UUID(), text: "Would you rather receive a playlist made for you or a personalized poem?", optionA: "Playlist", optionB: "Poem", challengeA: "Name a song you'd add.", challengeB: "Read a poem line."),
    Question(id: UUID(), text: "Would you rather be serenaded or slow danced with?", optionA: "Serenaded", optionB: "Slow danced", challengeA: "Sing a line.", challengeB: "Dance for a moment."),
    Question(id: UUID(), text: "Would you rather have your hand held or your hair touched?", optionA: "Hand held", optionB: "Hair touched", challengeA: "Show how you'd hold it.", challengeB: "Describe the touch."),
    Question(id: UUID(), text: "Would you rather receive a surprise visit or a surprise letter?", optionA: "Visit", optionB: "Letter", challengeA: "React to the visit.", challengeB: "Read the letter."),
    Question(id: UUID(), text: "Would you rather be teased with words or with glances?", optionA: "Words", optionB: "Glances", challengeA: "Say the teasing line.", challengeB: "Give the teasing look."),
    Question(id: UUID(), text: "Would you rather dance in the rain or talk under the stars?", optionA: "Dance in rain", optionB: "Talk under stars", challengeA: "Act out the dance.", challengeB: "Describe the conversation."),
    Question(id: UUID(), text: "Would you rather get a compliment in public or in private?", optionA: "Public", optionB: "Private", challengeA: "Give a public compliment.", challengeB: "Give a private one."),
    Question(id: UUID(), text: "Would you rather send a cheeky meme or a mysterious text?", optionA: "Cheeky meme", optionB: "Mysterious text", challengeA: "Describe the meme.", challengeB: "Write the text."),
    Question(id: UUID(), text: "Would you rather wear matching outfits or matching accessories?", optionA: "Outfits", optionB: "Accessories", challengeA: "Describe the outfit.", challengeB: "Describe the accessory."),
    Question(id: UUID(), text: "Would you rather share a dessert or share a blanket?", optionA: "Dessert", optionB: "Blanket", challengeA: "Describe the dessert.", challengeB: "Describe the blanket."),
    Question(id: UUID(), text: "Would you rather have a flirty nickname or a flirty catchphrase?", optionA: "Nickname", optionB: "Catchphrase", challengeA: "Say the nickname.", challengeB: "Say the catchphrase."),
    Question(id: UUID(), text: "Would you rather exchange inside jokes or inside secrets?", optionA: "Inside jokes", optionB: "Inside secrets", challengeA: "Tell the joke.", challengeB: "Tell the secret."),
    Question(id: UUID(), text: "Would you rather receive a midnight call or a sunrise message?", optionA: "Midnight call", optionB: "Sunrise message", challengeA: "Act the call.", challengeB: "Read the message."),
    Question(id: UUID(), text: "Would you rather be swept into a dance or pulled into a conversation?", optionA: "Dance", optionB: "Conversation", challengeA: "Start the dance.", challengeB: "Start the conversation."),
    Question(id: UUID(), text: "Would you rather hear a compliment about your laugh or your eyes?", optionA: "Laugh", optionB: "Eyes", challengeA: "Laugh now.", challengeB: "Describe your eyes."),
    Question(id: UUID(), text: "Would you rather trade playlists or trade secrets?", optionA: "Playlists", optionB: "Secrets", challengeA: "Share a song.", challengeB: "Share a secret."),
    Question(id: UUID(), text: "Would you rather go for a walk or stay in for a talk?", optionA: "Walk", optionB: "Talk", challengeA: "Describe the walk.", challengeB: "Describe the talk."),
    Question(id: UUID(), text: "Would you rather receive a love song or a love drawing?", optionA: "Song", optionB: "Drawing", challengeA: "Sing a line.", challengeB: "Describe the drawing."),
    Question(id: UUID(), text: "Would you rather play a truth game or a dare game?", optionA: "Truth", optionB: "Dare", challengeA: "Ask a truth.", challengeB: "Give a dare."),
    Question(id: UUID(), text: "Would you rather have a spontaneous trip or a planned getaway?", optionA: "Spontaneous", optionB: "Planned", challengeA: "Name the destination.", challengeB: "Describe the plan."),
    Question(id: UUID(), text: "Would you rather meet in a coffee shop or a rooftop bar?", optionA: "Coffee shop", optionB: "Rooftop bar", challengeA: "Describe the coffee shop vibe.", challengeB: "Describe the rooftop vibe."),
    Question(id: UUID(), text: "Would you rather exchange daily photos or daily quotes?", optionA: "Photos", optionB: "Quotes", challengeA: "Take a photo now.", challengeB: "Say a quote."),
    Question(id: UUID(), text: "Would you rather watch a sunset together or a sunrise?", optionA: "Sunset", optionB: "Sunrise", challengeA: "Describe the sunset.", challengeB: "Describe the sunrise."),
    Question(id: UUID(), text: "Would you rather share a secret hideout or a secret recipe?", optionA: "Hideout", optionB: "Recipe", challengeA: "Describe the hideout.", challengeB: "Describe the recipe."),
    Question(id: UUID(), text: "Would you rather get a kiss on the hand or the cheek?", optionA: "Hand", optionB: "Cheek", challengeA: "Act it out.", challengeB: "Describe it."),
    Question(id: UUID(), text: "Would you rather write your own vows or have them written for you?", optionA: "Write my own", optionB: "Have them written", challengeA: "Write a line.", challengeB: "Read a line."),
    Question(id: UUID(), text: "Would you rather give a compliment or receive one?", optionA: "Give", optionB: "Receive", challengeA: "Give one now.", challengeB: "React to one."),
    Question(id: UUID(), text: "Would you rather spend a rainy day indoors or outdoors?", optionA: "Indoors", optionB: "Outdoors", challengeA: "Describe indoors.", challengeB: "Describe outdoors."),
    Question(id: UUID(), text: "Would you rather get flowers or chocolates?", optionA: "Flowers", optionB: "Chocolates", challengeA: "Describe the flowers.", challengeB: "Describe the chocolates."),
    Question(id: UUID(), text: "Would you rather write a postcard or a long letter?", optionA: "Postcard", optionB: "Long letter", challengeA: "Write a postcard line.", challengeB: "Write a letter line."),
    Question(id: UUID(), text: "Would you rather receive a compliment about your outfit or your energy?", optionA: "Outfit", optionB: "Energy", challengeA: "Show your outfit.", challengeB: "Describe your energy."),
    Question(id: UUID(), text: "Would you rather take a photo together or draw each other?", optionA: "Photo", optionB: "Draw", challengeA: "Take the photo.", challengeB: "Draw them."),
    Question(id: UUID(), text: "Would you rather dance under fairy lights or under the moon?", optionA: "Fairy lights", optionB: "Moon", challengeA: "Act out the dance.", challengeB: "Describe the scene."),
    Question(id: UUID(), text: "Would you rather hear a whispered compliment or a loud cheer?", optionA: "Whispered compliment", optionB: "Loud cheer", challengeA: "Whisper it now.", challengeB: "Shout it now."),
    Question(id: UUID(), text: "Would you rather leave a trail of notes or a trail of clues?", optionA: "Notes", optionB: "Clues", challengeA: "Write a note.", challengeB: "Give a clue."),
    Question(id: UUID(), text: "Would you rather have a shared playlist or a shared journal?", optionA: "Playlist", optionB: "Journal", challengeA: "Add a song.", challengeB: "Add a journal entry."),
    Question(id: UUID(), text: "Would you rather get a surprise compliment or a surprise gift?", optionA: "Compliment", optionB: "Gift", challengeA: "Give the compliment.", challengeB: "Describe the gift."),
    Question(id: UUID(), text: "Would you rather share a hammock or a picnic blanket?", optionA: "Hammock", optionB: "Picnic blanket", challengeA: "Describe the hammock.", challengeB: "Describe the picnic."),
    Question(id: UUID(), text: "Would you rather have matching mugs or matching pajamas?", optionA: "Mugs", optionB: "Pajamas", challengeA: "Describe the mugs.", challengeB: "Describe the pajamas."),
    Question(id: UUID(), text: "Would you rather write in sand or carve in wood?", optionA: "Sand", optionB: "Wood", challengeA: "Write your message.", challengeB: "Describe your carving."),
    Question(id: UUID(), text: "Would you rather exchange playlists or recipes?", optionA: "Playlists", optionB: "Recipes", challengeA: "Share a song.", challengeB: "Share a recipe."),
    Question(id: UUID(), text: "Would you rather talk until sunrise or sleep early together?", optionA: "Talk until sunrise", optionB: "Sleep early", challengeA: "Describe the night.", challengeB: "Describe the early sleep."),
    Question(id: UUID(), text: "Would you rather have an inside nickname or an inside handshake?", optionA: "Nickname", optionB: "Handshake", challengeA: "Say the nickname.", challengeB: "Do the handshake."),
    Question(id: UUID(), text: "Would you rather have a song written for you or a story written about you?", optionA: "Song", optionB: "Story", challengeA: "Sing the song line.", challengeB: "Read the story line.")
])

