import Foundation

let shakespeare = Deck(name: "Shakespearean Dilemmas", icon: "🎭", questions: [
    Question(id: UUID(), text: "Would you rather woo your love with sonnets or with grand gestures?", optionA: "Sonnets", optionB: "Grand gestures", challengeA: "Recite a line of a sonnet.", challengeB: "Describe your grand gesture."),
    Question(id: UUID(), text: "Would you rather be star-crossed lovers or cunning tricksters?", optionA: "Star-crossed lovers", optionB: "Cunning tricksters", challengeA: "Act out a tragic scene.", challengeB: "Plot a playful prank."),
    Question(id: UUID(), text: "Would you rather attend a masquerade ball or a royal feast?", optionA: "Masquerade ball", optionB: "Royal feast", challengeA: "Describe your mask.", challengeB: "Describe your feast dish."),
    Question(id: UUID(), text: "Would you rather duel with words or with swords?", optionA: "Words", optionB: "Swords", challengeA: "Deliver a witty insult.", challengeB: "Pretend to fence."),
    Question(id: UUID(), text: "Would you rather be a witty fool or a noble hero?", optionA: "Witty fool", optionB: "Noble hero", challengeA: "Say a clever joke.", challengeB: "Strike a heroic pose."),
    Question(id: UUID(), text: "Would you rather fall for a mysterious stranger or a childhood friend?", optionA: "Mysterious stranger", optionB: "Childhood friend", challengeA: "Describe your stranger.", challengeB: "Recall a childhood memory."),
    Question(id: UUID(), text: "Would you rather speak in iambic pentameter or modern slang?", optionA: "Iambic pentameter", optionB: "Modern slang", challengeA: "Speak a line.", challengeB: "Say a slang phrase."),
    Question(id: UUID(), text: "Would you rather survive a shipwreck or a poison plot?", optionA: "Shipwreck", optionB: "Poison plot", challengeA: "Describe the storm.", challengeB: "Explain your escape."),
    Question(id: UUID(), text: "Would you rather be bewitched by a fairy or haunted by a ghost?", optionA: "Bewitched by fairy", optionB: "Haunted by ghost", challengeA: "Describe the fairy's spell.", challengeB: "Describe the ghost."),
    Question(id: UUID(), text: "Would you rather have your love tested by time or by distance?", optionA: "Tested by time", optionB: "Tested by distance", challengeA: "Describe your patience.", challengeB: "Describe your longing."),
    Question(id: UUID(), text: "Would you rather confess your love publicly or in secret?", optionA: "Public confession", optionB: "Secret confession", challengeA: "Make a public declaration.", challengeB: "Whisper your secret."),
    Question(id: UUID(), text: "Would you rather wear a crown or a fool’s cap?", optionA: "Crown", optionB: "Fool’s cap", challengeA: "Describe your rule.", challengeB: "Tell a joke."),
    Question(id: UUID(), text: "Would you rather be a tragic hero or a comedic sidekick?", optionA: "Tragic hero", optionB: "Comedic sidekick", challengeA: "Say a tragic line.", challengeB: "Make a funny comment."),
    Question(id: UUID(), text: "Would you rather have your fate decided by a coin toss or by a duel?", optionA: "Coin toss", optionB: "Duel", challengeA: "Call the coin.", challengeB: "Show your duel stance."),
    Question(id: UUID(), text: "Would you rather live in a castle or a forest cottage?", optionA: "Castle", optionB: "Forest cottage", challengeA: "Describe the castle.", challengeB: "Describe the cottage."),
    Question(id: UUID(), text: "Would you rather be betrayed by a friend or a lover?", optionA: "Friend", optionB: "Lover", challengeA: "Describe the betrayal.", challengeB: "Describe your feelings."),
    Question(id: UUID(), text: "Would you rather be cursed to forget your true love or cursed to never speak again?", optionA: "Forget true love", optionB: "Never speak", challengeA: "Show your sorrow.", challengeB: "Mime a scene."),
    Question(id: UUID(), text: "Would you rather attend a royal wedding or a secret midnight meeting?", optionA: "Royal wedding", optionB: "Secret meeting", challengeA: "Describe the wedding.", challengeB: "Describe the meeting."),
    Question(id: UUID(), text: "Would you rather be a poet or a warrior?", optionA: "Poet", optionB: "Warrior", challengeA: "Recite a poem line.", challengeB: "Show your battle cry."),
    Question(id: UUID(), text: "Would you rather have your love story told for centuries or live quietly in peace?", optionA: "Told for centuries", optionB: "Live in peace", challengeA: "Describe your story.", challengeB: "Describe your peace."),
    Question(id: UUID(), text: "Would you rather escape prison with wit or with strength?", optionA: "Wit", optionB: "Strength", challengeA: "Make a clever escape plan.", challengeB: "Show your strength."),
    Question(id: UUID(), text: "Would you rather duel for honor or negotiate for peace?", optionA: "Duel", optionB: "Negotiate", challengeA: "Show your duel pose.", challengeB: "Make a peace proposal."),
    Question(id: UUID(), text: "Would you rather be a misunderstood villain or a flawed hero?", optionA: "Villain", optionB: "Hero", challengeA: "Explain your villainy.", challengeB: "Explain your flaw."),
    Question(id: UUID(), text: "Would you rather write a love letter or a dramatic monologue?", optionA: "Love letter", optionB: "Monologue", challengeA: "Read a line aloud.", challengeB: "Perform a dramatic line."),
    Question(id: UUID(), text: "Would you rather meet the Bard himself or a famous character?", optionA: "Bard", optionB: "Character", challengeA: "Ask a question.", challengeB: "Imitate the character."),
    Question(id: UUID(), text: "Would you rather be cursed with endless love or eternal wisdom?", optionA: "Endless love", optionB: "Eternal wisdom", challengeA: "Describe your love.", challengeB: "Share your wisdom."),
    Question(id: UUID(), text: "Would you rather play Puck or Juliet?", optionA: "Puck", optionB: "Juliet", challengeA: "Say a mischievous line.", challengeB: "Say a romantic line."),
    Question(id: UUID(), text: "Would you rather have your dialogue in prose or poetry?", optionA: "Prose", optionB: "Poetry", challengeA: "Speak a prose line.", challengeB: "Speak a poetic line."),
    Question(id: UUID(), text: "Would you rather be lost in a magical forest or trapped in a castle tower?", optionA: "Magical forest", optionB: "Castle tower", challengeA: "Describe the forest.", challengeB: "Describe the tower."),
    Question(id: UUID(), text: "Would you rather have your fate decided by the stars or by your own hand?", optionA: "Stars", optionB: "Own hand", challengeA: "Describe your fate.", challengeB: "Describe your choice."),
    Question(id: UUID(), text: "Would you rather have a tragic love story or a comedic one?", optionA: "Tragic", optionB: "Comedic", challengeA: "Say a tragic line.", challengeB: "Say a funny line."),
    Question(id: UUID(), text: "Would you rather fight for your love or flee to freedom?", optionA: "Fight", optionB: "Flee", challengeA: "Show your battle cry.", challengeB: "Describe your escape."),
    Question(id: UUID(), text: "Would you rather live as a royal or as a wandering bard?", optionA: "Royal", optionB: "Bard", challengeA: "Describe your crown.", challengeB: "Sing a bard's song."),
    Question(id: UUID(), text: "Would you rather be cursed to speak only in riddles or only in song?", optionA: "Riddles", optionB: "Song", challengeA: "Say a riddle.", challengeB: "Sing a line."),
    Question(id: UUID(), text: "Would you rather have your secret love discovered or keep it hidden forever?", optionA: "Discovered", optionB: "Hidden", challengeA: "Reveal your secret.", challengeB: "Pretend to hide."),
    Question(id: UUID(), text: "Would you rather be a loyal friend or a passionate lover?", optionA: "Loyal friend", optionB: "Passionate lover", challengeA: "Show loyalty.", challengeB: "Show passion."),
    Question(id: UUID(), text: "Would you rather recite Shakespeare by heart or write your own play?", optionA: "Recite", optionB: "Write", challengeA: "Say a line.", challengeB: "Describe your play."),
    Question(id: UUID(), text: "Would you rather have a magical potion for love or for wisdom?", optionA: "Love potion", optionB: "Wisdom potion", challengeA: "Describe the potion.", challengeB: "Describe its effect."),
    Question(id: UUID(), text: "Would you rather be famous for a tragic death or a heroic victory?", optionA: "Tragic death", optionB: "Heroic victory", challengeA: "Describe your death.", challengeB: "Describe your victory."),
    Question(id: UUID(), text: "Would you rather have your true love be a secret admirer or a known rival?", optionA: "Secret admirer", optionB: "Known rival", challengeA: "Describe your admirer.", challengeB: "Describe your rival."),
    Question(id: UUID(), text: "Would you rather be the star of a comedy or a tragedy?", optionA: "Comedy", optionB: "Tragedy", challengeA: "Make a funny face.", challengeB: "Show a sad face."),
    Question(id: UUID(), text: "Would you rather dance at a midsummer night’s ball or a harvest festival?", optionA: "Midsummer ball", optionB: "Harvest festival", challengeA: "Describe your dance.", challengeB: "Describe the festival."),
    Question(id: UUID(), text: "Would you rather face a jealous rival or a meddling parent?", optionA: "Jealous rival", optionB: "Meddling parent", challengeA: "Describe your rival.", challengeB: "Describe the parent."),
    Question(id: UUID(), text: "Would you rather wear a flowing cloak or a shining armor?", optionA: "Cloak", optionB: "Armor", challengeA: "Describe your cloak.", challengeB: "Describe your armor."),
    Question(id: UUID(), text: "Would you rather live in Verona or in the enchanted forest?", optionA: "Verona", optionB: "Enchanted forest", challengeA: "Describe Verona.", challengeB: "Describe the forest."),
    Question(id: UUID(), text: "Would you rather be loved for your wit or your beauty?", optionA: "Wit", optionB: "Beauty", challengeA: "Deliver a witty line.", challengeB: "Describe your beauty."),
    Question(id: UUID(), text: "Would you rather have a magic spell go right or hilariously wrong?", optionA: "Go right", optionB: "Go wrong", challengeA: "Describe your success.", challengeB: "Describe your fail."),
    Question(id: UUID(), text: "Would you rather write a love letter or a farewell note?", optionA: "Love letter", optionB: "Farewell note", challengeA: "Read your letter.", challengeB: "Read your note."),
    Question(id: UUID(), text: "Would you rather be the hero in a comedy or the villain in a tragedy?", optionA: "Hero in comedy", optionB: "Villain in tragedy", challengeA: "Say a heroic line.", challengeB: "Say a villainous line."),
    Question(id: UUID(), text: "Would you rather be a clever servant or a powerful noble?", optionA: "Clever servant", optionB: "Powerful noble", challengeA: "Say a clever line.", challengeB: "Declare your power."),
    Question(id: UUID(), text: "Would you rather have your heart broken or your pride wounded?", optionA: "Heart broken", optionB: "Pride wounded", challengeA: "Show sadness.", challengeB: "Show indignation."),
    Question(id: UUID(), text: "Would you rather be immortal or have one perfect day?", optionA: "Immortal", optionB: "One perfect day", challengeA: "Describe eternity.", challengeB: "Describe your perfect day."),
    Question(id: UUID(), text: "Would you rather end the play with a dance or a duel?", optionA: "Dance", optionB: "Duel", challengeA: "Show your dance move.", challengeB: "Show your duel stance."),
    Question(id: UUID(), text: "Would you rather be remembered for your wit or your courage?", optionA: "Wit", optionB: "Courage", challengeA: "Tell a joke.", challengeB: "Show bravery."),
    Question(id: UUID(), text: "Would you rather lose your memory or your voice?", optionA: "Memory", optionB: "Voice", challengeA: "Pretend to forget.", challengeB: "Mime a scene."),
    Question(id: UUID(), text: "Would you rather be the king’s jester or the queen’s confidant?", optionA: "Jester", optionB: "Confidant", challengeA: "Make a joke.", challengeB: "Share a secret."),
    Question(id: UUID(), text: "Would you rather be caught in a love triangle or a political intrigue?", optionA: "Love triangle", optionB: "Political intrigue", challengeA: "Describe your feelings.", challengeB: "Describe your plan."),
    Question(id: UUID(), text: "Would you rather wear a garland of roses or a crown of thorns?", optionA: "Garland of roses", optionB: "Crown of thorns", challengeA: "Describe the roses.", challengeB: "Describe the thorns."),
    Question(id: UUID(), text: "Would you rather fall asleep in a moonlit garden or a cozy hearth?", optionA: "Moonlit garden", optionB: "Cozy hearth", challengeA: "Describe the garden.", challengeB: "Describe the hearth."),
    Question(id: UUID(), text: "Would you rather make a vow of silence or a vow of truth?", optionA: "Silence", optionB: "Truth", challengeA: "Act silently.", challengeB: "Tell a truth."),
])

